package app

import (
	"time"

	"github.com/oibacidem/lims-hl-seven/internal/entity"
)

var seedPatient = []entity.Patient{
	{
		ID:          1,
		FirstName:   "Pasien",
		LastName:    "Pertama",
		Birthdate:   time.Date(1995, time.January, 1, 0, 0, 0, 0, time.UTC),
		Sex:         "M",
		PhoneNumber: "",
		Location:    "",
		Address:     "",
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	},
	{
		ID:          2,
		FirstName:   "Pasien",
		LastName:    "Kedua",
		Birthdate:   time.Date(2002, time.October, 23, 0, 0, 0, 0, time.UTC),
		Sex:         "F",
		PhoneNumber: "",
		Location:    "",
		Address:     "",
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	},
	{
		ID:          3,
		FirstName:   "Pasien",
		LastName:    "Ketiga",
		Birthdate:   time.Date(1998, time.February, 20, 0, 0, 0, 0, time.UTC),
		Sex:         "F",
		PhoneNumber: "",
		Location:    "",
		Address:     "",
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	},
}

var seedDataTestType = []entity.TestType{
	// Hematology Tests
	// Red Series
	{Name: "RBC", Code: "RBC", Unit: "10^6/µL", LowRefRange: 4.5, HighRefRange: 5.9, Category: "Hematology", SubCategory: "Red Series", Description: "Red blood cell count."},
	{Name: "HEMOGLOBIN", Code: "HEMOGLOBIN", Unit: "g/dL", LowRefRange: 13.5, HighRefRange: 17.5, Category: "Hematology", SubCategory: "Red Series", Description: "Hemoglobin concentration in blood."},
	{Name: "HEMATOCRIT", Code: "HEMATOCRIT", Unit: "%", LowRefRange: 41, HighRefRange: 50, Category: "Hematology", SubCategory: "Red Series", Description: "Percentage of red blood cells in blood."},
	{Name: "MCV", Code: "MCV", Unit: "fL", LowRefRange: 80, HighRefRange: 100, Category: "Hematology", SubCategory: "Red Series", Description: "Mean corpuscular volume (size of red blood cells)."},
	{Name: "MCH", Code: "MCH", Unit: "pg", LowRefRange: 27, HighRefRange: 31, Category: "Hematology", SubCategory: "Red Series", Description: "Mean corpuscular hemoglobin (average hemoglobin per red blood cell)."},
	{Name: "MCHC", Code: "MCHC", Unit: "g/dL", LowRefRange: 32, HighRefRange: 36, Category: "Hematology", SubCategory: "Red Series", Description: "Mean corpuscular hemoglobin concentration."},
	{Name: "RDW", Code: "RDW", Unit: "%", LowRefRange: 11.5, HighRefRange: 14.5, Category: "Hematology", SubCategory: "Red Series", Description: "Red cell distribution width (variation in size of red blood cells)."},
	{Name: "RDW_CV", Code: "RDW_CV", Unit: "%", LowRefRange: 11.5, HighRefRange: 14.5, Category: "Hematology", SubCategory: "Red Series", Description: "Coefficient of variation in red cell distribution width."},
	{Name: "RDW_SD", Code: "RDW_SD", Unit: "fL", LowRefRange: 37, HighRefRange: 54, Category: "Hematology", SubCategory: "Red Series", Description: "Standard deviation in red cell distribution width."},

	// White Series
	{Name: "WBC", Code: "WBC", Unit: "10^3/µL", LowRefRange: 4.0, HighRefRange: 11.0, Category: "Hematology", SubCategory: "White Series", Description: "White blood cell count."},
	{Name: "NEUTROPHILS", Code: "NEUTROPHILS", Unit: "%", LowRefRange: 40, HighRefRange: 70, Category: "Hematology", SubCategory: "White Series", Description: "Percentage of neutrophils in white blood cells."},
	{Name: "LYMPHOCYTES", Code: "LYMPHOCYTES", Unit: "%", LowRefRange: 20, HighRefRange: 40, Category: "Hematology", SubCategory: "White Series", Description: "Percentage of lymphocytes in white blood cells."},
	{Name: "MONOCYTES", Code: "MONOCYTES", Unit: "%", LowRefRange: 2, HighRefRange: 8, Category: "Hematology", SubCategory: "White Series", Description: "Percentage of monocytes in white blood cells."},
	{Name: "EOSINOPHILS", Code: "EOSINOPHILS", Unit: "%", LowRefRange: 1, HighRefRange: 4, Category: "Hematology", SubCategory: "White Series", Description: "Percentage of eosinophils in white blood cells."},
	{Name: "BASOPHILS", Code: "BASOPHILS", Unit: "%", LowRefRange: 0, HighRefRange: 1, Category: "Hematology", SubCategory: "White Series", Description: "Percentage of basophils in white blood cells."},
	{Name: "LCR", Code: "LCR", Unit: "%", LowRefRange: 0, HighRefRange: 10, Category: "Hematology", SubCategory: "White Series", Description: "Large cell ratio in white blood cells."},
	{Name: "LCC", Code: "LCC", Unit: "10^3/µL", LowRefRange: 0, HighRefRange: 0.4, Category: "Hematology", SubCategory: "White Series", Description: "Large cell count in white blood cells."},
	{Name: "MID", Code: "MID", Unit: "10^3/µL", LowRefRange: 0.1, HighRefRange: 0.9, Category: "Hematology", SubCategory: "White Series", Description: "Mid-size cells in blood (includes monocytes, eosinophils, and basophils)."},
	{Name: "MID#", Code: "MID#", Unit: "10^3/µL", LowRefRange: 0.1, HighRefRange: 0.9, Category: "Hematology", SubCategory: "White Series", Description: "Absolute count of mid-size cells in blood."},

	// Platelets
	{Name: "PLATELET COUNT", Code: "PLATELET COUNT", Unit: "10^3/µL", LowRefRange: 150, HighRefRange: 450, Category: "Hematology", SubCategory: "Platelets", Description: "Platelet count in blood."},
	{Name: "MPV", Code: "MPV", Unit: "fL", LowRefRange: 7.5, HighRefRange: 11.5, Category: "Hematology", SubCategory: "Platelets", Description: "Mean platelet volume."},
	{Name: "PDW", Code: "PDW", Unit: "%", LowRefRange: 10, HighRefRange: 18, Category: "Hematology", SubCategory: "Platelets", Description: "Platelet distribution width (variation in size of platelets)."},
	{Name: "PCT", Code: "PCT", Unit: "%", LowRefRange: 0.2, HighRefRange: 0.5, Category: "Hematology", SubCategory: "Platelets", Description: "Plateletcrit (total platelet mass in blood)."},
	{Name: "P_LCR", Code: "P_LCR", Unit: "%", LowRefRange: 0, HighRefRange: 30, Category: "Hematology", SubCategory: "Platelets", Description: "Platelet large cell ratio."},
	{Name: "P_LCC", Code: "P_LCC", Unit: "10^3/µL", LowRefRange: 0, HighRefRange: 15, Category: "Hematology", SubCategory: "Platelets", Description: "Platelet large cell count."},

	// Observation Tests
	{Name: "ACE", Code: "ACE", Unit: "U/L", LowRefRange: 10, HighRefRange: 40, Category: "Observation", SubCategory: "Other", Description: "Angiotensin-converting enzyme activity."},
	{Name: "ACID GLYCO BIR", Code: "ACID GLYCO BIR", Unit: "mg/dL", LowRefRange: 5, Category: "Observation", HighRefRange: 15, SubCategory: "Other", Description: "Acid glycoprotein test."},
	{Name: "ADA", Code: "ADA", Unit: "U/L", LowRefRange: 10, HighRefRange: 45, Category: "Observation", SubCategory: "Other", Description: "Adenosine deaminase enzyme activity."},
	{Name: "ASO", Code: "ASO", Unit: "IU/mL", LowRefRange: 0, HighRefRange: 200, Category: "Observation", SubCategory: "Other", Description: "Anti-streptolysin O titer test."},
	{Name: "ATIII", Code: "ATIII", Unit: "%", LowRefRange: 70, HighRefRange: 120, Category: "Observation", SubCategory: "Other", Description: "Antithrombin III activity test."},
	{Name: "COMPLEMENT C3BIR", Code: "COMPLEMENT C3BIR", Unit: "mg/dL", LowRefRange: 90, HighRefRange: 180, Category: "Observation", SubCategory: "Other", Description: "Complement C3 test."},
	{Name: "COMPLEMENT C4BIR", Code: "COMPLEMENT C4BIR", Unit: "mg/dL", LowRefRange: 10, HighRefRange: 40, Category: "Observation", SubCategory: "Other", Description: "Complement C4 test."},
	{Name: "CRPER", Code: "CRPER", Unit: "", LowRefRange: 0, HighRefRange: 0, Category: "Observation", SubCategory: "Other", Description: "Observation for CRPER."},
	{Name: "DUMMY", Code: "DUMMY", Unit: "", LowRefRange: 0, HighRefRange: 0, Category: "Observation", SubCategory: "Other", Description: "Dummy observation for testing purposes."},

	// Biochemistry Tests
	{Name: "ALBUMIN", Code: "ALBUMIN", Unit: "g/dL", LowRefRange: 3.5, HighRefRange: 5.0, Category: "Biochemistry", SubCategory: "Liver Function", Description: "Measurement of serum albumin levels."},
	{Name: "ALBUMIN-MAU", Code: "ALBUMIN-MAU", Unit: "mg/g", LowRefRange: 0, HighRefRange: 30, Category: "Biochemistry", SubCategory: "Kidney Function", Description: "Microalbuminuria for kidney health assessment."},
	{Name: "ALP-AMP", Code: "ALP-AMP", Unit: "U/L", LowRefRange: 40, HighRefRange: 120, Category: "Biochemistry", SubCategory: "Liver Function", Description: "Alkaline phosphatase enzyme activity test (AMP method)."},
	{Name: "ALP-DEA", Code: "ALP-DEA", Unit: "U/L", LowRefRange: 40, HighRefRange: 120, Category: "Biochemistry", SubCategory: "Liver Function", Description: "Alkaline phosphatase enzyme activity test (DEA method)."},
	{Name: "ALPHA-GLUCOSIDAS", Code: "ALPHA-GLUCOSIDAS", Unit: "U/L", LowRefRange: 20, HighRefRange: 80, Category: "Biochemistry", SubCategory: "Metabolism", Description: "Alpha-glucosidase enzyme activity."},
	{Name: "ALT-GPT", Code: "ALT-GPT", Unit: "U/L", LowRefRange: 7, HighRefRange: 56, Category: "Biochemistry", SubCategory: "Liver Function", Description: "Alanine transaminase enzyme levels."},
	{Name: "AMMONIA", Code: "AMMONIA", Unit: "µg/dL", LowRefRange: 15, HighRefRange: 45, Category: "Biochemistry", SubCategory: "Other", Description: "Measurement of blood ammonia levels."},
	{Name: "AMYLASE DIRECT", Code: "AMYLASE DIRECT", Unit: "U/L", LowRefRange: 30, HighRefRange: 110, Category: "Biochemistry", SubCategory: "Other", Description: "Serum amylase enzyme activity test."},
	{Name: "AMYLASE EPS", Code: "AMYLASE EPS", Unit: "U/L", LowRefRange: 30, HighRefRange: 110, Category: "Biochemistry", SubCategory: "Other", Description: "Amylase test using EPS method."},
	{Name: "AMYLASE PANCREAT", Code: "AMYLASE PANCREAT", Unit: "U/L", LowRefRange: 30, HighRefRange: 110, Category: "Biochemistry", SubCategory: "Other", Description: "Pancreatic amylase test."},
	{Name: "APO AI", Code: "APO AI", Unit: "mg/dL", LowRefRange: 100, HighRefRange: 180, Category: "Biochemistry", SubCategory: "Other", Description: "Apolipoprotein AI levels."},
	{Name: "APO B", Code: "APO B", Unit: "mg/dL", LowRefRange: 60, HighRefRange: 120, Category: "Biochemistry", SubCategory: "Other", Description: "Apolipoprotein B levels."},
	{Name: "AST-GOT", Code: "AST-GOT", Unit: "U/L", LowRefRange: 10, HighRefRange: 40, Category: "Biochemistry", SubCategory: "Liver Function", Description: "Aspartate transaminase enzyme levels."},
	{Name: "AST-GOT-VERIF", Code: "AST-GOT-VERIF", Unit: "U/L", LowRefRange: 10, HighRefRange: 40, Category: "Biochemistry", SubCategory: "Liver Function", Description: "Aspartate transaminase levels verification."},
	{Name: "B2 MICROGLOBULIN", Code: "B2 MICROGLOBULIN", Unit: "mg/L", LowRefRange: 1.5, HighRefRange: 2.5, Category: "Biochemistry", SubCategory: "Other", Description: "Beta-2 microglobulin levels."},
	{Name: "B-HYDROXYBUTYRAT", Code: "B-HYDROXYBUTYRAT", Unit: "mmol/L", LowRefRange: 0.02, HighRefRange: 0.30, Category: "Biochemistry", SubCategory: "Metabolism", Description: "Beta-hydroxybutyrate levels."},
	{Name: "BILI DIRECT DPD", Code: "BILI DIRECT DPD", Unit: "mg/dL", LowRefRange: 0.0, HighRefRange: 0.4, Category: "Biochemistry", SubCategory: "Liver Function", Description: "Direct bilirubin test (DPD method)."},
	{Name: "BILI T NEWBORN", Code: "BILI T NEWBORN", Unit: "mg/dL", LowRefRange: 0.0, HighRefRange: 12.0, Category: "Biochemistry", SubCategory: "Liver Function", Description: "Total bilirubin test for newborns."},
	{Name: "BILI TOTAL DPD", Code: "BILI TOTAL DPD", Unit: "mg/dL", LowRefRange: 0.2, HighRefRange: 1.2, Category: "Biochemistry", SubCategory: "Liver Function", Description: "Total bilirubin test (DPD method)."},
	{Name: "BILIRUBIN DIRECT", Code: "BILIRUBIN DIRECT", Unit: "mg/dL", LowRefRange: 0.0, HighRefRange: 0.3, Category: "Biochemistry", SubCategory: "Liver Function", Description: "Measurement of direct bilirubin levels."},
	{Name: "BILIRUBIN TOTAL", Code: "BILIRUBIN TOTAL", Unit: "mg/dL", LowRefRange: 0.3, HighRefRange: 1.2, Category: "Biochemistry", SubCategory: "Liver Function", Description: "Measurement of total bilirubin levels."},
	{Name: "CALCIUM ARSENAZO", Code: "CALCIUM ARSENAZO", Unit: "mg/dL", LowRefRange: 8.5, HighRefRange: 10.5, Category: "Biochemistry", SubCategory: "Electrolytes", Description: "Calcium test using Arsenazo III method."},
	{Name: "CALCIUM CPC", Code: "CALCIUM CPC", Unit: "mg/dL", LowRefRange: 8.5, HighRefRange: 10.5, Category: "Biochemistry", SubCategory: "Electrolytes", Description: "Calcium test using CPC method."},
	{Name: "CARBON DIOXIDE", Code: "CARBON DIOXIDE", Unit: "mmol/L", LowRefRange: 23, HighRefRange: 29, Category: "Biochemistry", SubCategory: "Other", Description: "Measurement of serum bicarbonate levels."},
	{Name: "CHOL HDL DIRECT", Code: "CHOL HDL DIRECT", Unit: "mg/dL", LowRefRange: 40, HighRefRange: 60, Category: "Biochemistry", SubCategory: "Metabolism", Description: "High-density lipoprotein (HDL) cholesterol test."},
	{Name: "CHOL LDL DIRECT", Code: "CHOL LDL DIRECT", Unit: "mg/dL", LowRefRange: 70, HighRefRange: 130, Category: "Biochemistry", SubCategory: "Metabolism", Description: "Low-density lipoprotein (LDL) cholesterol test."},
	{Name: "CHOLESTEROL", Code: "CHOLESTEROL", Unit: "mg/dL", LowRefRange: 125, HighRefRange: 200, Category: "Biochemistry", SubCategory: "Metabolism", Description: "Total cholesterol levels."},
	{Name: "CITRATE", Code: "CITRATE", Unit: "mmol/L", LowRefRange: 0, HighRefRange: 0, Category: "Biochemistry", SubCategory: "Other", Description: "Citrate levels measurement."},
	{Name: "CK", Code: "CK", Unit: "U/L", LowRefRange: 38, HighRefRange: 174, Category: "Biochemistry", SubCategory: "Metabolism", Description: "Creatine kinase levels."},
	{Name: "CK-MB", Code: "CK-MB", Unit: "U/L", LowRefRange: 0, HighRefRange: 25, Category: "Biochemistry", SubCategory: "Metabolism", Description: "Creatine kinase-MB fraction levels."},
	{Name: "CRP", Code: "CRP", Unit: "mg/L", LowRefRange: 0, HighRefRange: 10, Category: "Biochemistry", SubCategory: "Other", Description: "C-reactive protein levels."},
	{Name: "CRPHS", Code: "CRPHS", Unit: "mg/L", LowRefRange: 0, HighRefRange: 10, Category: "Biochemistry", SubCategory: "Other", Description: "High-sensitivity C-reactive protein levels."},
	{Name: "D-DIMER", Code: "D-DIMER", Unit: "mg/L", LowRefRange: 0.0, HighRefRange: 0.5, Category: "Biochemistry", SubCategory: "Other", Description: "D-dimer test for clot formation."},
	{Name: "ETHANOL", Code: "ETHANOL", Unit: "mg/dL", LowRefRange: 0, HighRefRange: 50, Category: "Biochemistry", SubCategory: "Other", Description: "Ethanol levels in blood."},
	{Name: "FERRITIN", Code: "FERRITIN", Unit: "ng/mL", LowRefRange: 20, HighRefRange: 300, Category: "Biochemistry", SubCategory: "Other", Description: "Ferritin levels to assess iron stores."},
	{Name: "FIBRINOGEN", Code: "FIBRINOGEN", Unit: "mg/dL", LowRefRange: 200, HighRefRange: 400, Category: "Biochemistry", SubCategory: "Other", Description: "Fibrinogen levels in blood plasma."},
	{Name: "FRUCTOSE", Code: "FRUCTOSE", Unit: "mg/dL", LowRefRange: 0, HighRefRange: 0, Category: "Biochemistry", SubCategory: "Other", Description: "Fructose levels in the body."},
	{Name: "G6PDH", Code: "G6PDH", Unit: "U/L", LowRefRange: 4.6, HighRefRange: 13.5, Category: "Biochemistry", SubCategory: "Metabolism", Description: "G6PDH enzyme activity levels."},
	{Name: "GAMMA-GT", Code: "GAMMA-GT", Unit: "U/L", LowRefRange: 9, HighRefRange: 48, Category: "Biochemistry", SubCategory: "Liver Function", Description: "Gamma-glutamyl transferase enzyme levels."},
	{Name: "GLUCOSE", Code: "GLUCOSE", Unit: "mg/dL", LowRefRange: 70, HighRefRange: 99, Category: "Biochemistry", SubCategory: "Metabolism", Description: "Blood glucose levels."},
	{Name: "GLUCOSE-HK", Code: "GLUCOSE-HK", Unit: "mg/dL", LowRefRange: 70, HighRefRange: 99, Category: "Biochemistry", SubCategory: "Metabolism", Description: "Blood glucose using hexokinase method."},
	{Name: "GLUCOSE-VERIF", Code: "GLUCOSE-VERIF", Unit: "mg/dL", LowRefRange: 70, HighRefRange: 99, Category: "Biochemistry", SubCategory: "Metabolism", Description: "Blood glucose verification."},
	{Name: "HAPTOGLOBIN", Code: "HAPTOGLOBIN", Unit: "mg/dL", LowRefRange: 40, HighRefRange: 180, Category: "Biochemistry", SubCategory: "Other", Description: "Haptoglobin levels in blood."},
	{Name: "HBA1C-DIRECT", Code: "HBA1C-DIR", Unit: "%", LowRefRange: 4.0, HighRefRange: 5.6, Category: "Biochemistry", SubCategory: "Metabolism", Description: "Direct measurement of HbA1c for diabetes monitoring."},
	{Name: "HOMOCYSTEINE", Code: "HOMOCYSTEINE", Unit: "µmol/L", LowRefRange: 4, HighRefRange: 15, Category: "Biochemistry", SubCategory: "Metabolism", Description: "Homocysteine levels in blood."},
	{Name: "IGA BIR", Code: "IGA BIR", Unit: "mg/dL", LowRefRange: 70, HighRefRange: 400, Category: "Biochemistry", SubCategory: "Other", Description: "IgA antibody levels in blood."},
	{Name: "IGG BIR", Code: "IGG BIR", Unit: "mg/dL", LowRefRange: 700, HighRefRange: 1600, Category: "Biochemistry", SubCategory: "Other", Description: "IgG antibody levels in blood."},
	{Name: "IGM BIR", Code: "IGM BIR", Unit: "mg/dL", LowRefRange: 40, HighRefRange: 230, Category: "Biochemistry", SubCategory: "Other", Description: "IgM antibody levels in blood."},
	{Name: "IRON FERROZINE", Code: "IRON FERROZINE", Unit: "µg/dL", LowRefRange: 50, HighRefRange: 170, Category: "Biochemistry", SubCategory: "Metabolism", Description: "Iron levels using ferrozine method."},
	{Name: "LACTATE", Code: "LACTATE", Unit: "mmol/L", LowRefRange: 0.5, HighRefRange: 2.2, Category: "Biochemistry", SubCategory: "Metabolism", Description: "Blood lactate levels."},
	{Name: "LDH", Code: "LDH", Unit: "U/L", LowRefRange: 135, HighRefRange: 225, Category: "Biochemistry", SubCategory: "Other", Description: "Lactate dehydrogenase levels in blood."},
	{Name: "LDH IFCC", Code: "LDH IFCC", Unit: "U/L", LowRefRange: 135, HighRefRange: 225, Category: "Biochemistry", SubCategory: "Other", Description: "Lactate dehydrogenase using IFCC method."},
	{Name: "LIPASE", Code: "LIPASE", Unit: "U/L", LowRefRange: 0, HighRefRange: 160, Category: "Biochemistry", SubCategory: "Other", Description: "Lipase enzyme levels for pancreatic health."},
	{Name: "LIPASE DGGR", Code: "LIPASE DGGR", Unit: "U/L", LowRefRange: 0, HighRefRange: 160, Category: "Biochemistry", SubCategory: "Other", Description: "Lipase enzyme test using DGGR method."},
	{Name: "MAGNESIUM", Code: "MAGNESIUM", Unit: "mg/dL", LowRefRange: 1.7, HighRefRange: 2.2, Category: "Biochemistry", SubCategory: "Electrolytes", Description: "Magnesium levels in blood."},
	{Name: "NEFA", Code: "NEFA", Unit: "mmol/L", LowRefRange: 0, HighRefRange: 0, Category: "Biochemistry", SubCategory: "Metabolism", Description: "Non-esterified fatty acid levels."},
	{Name: "OXALATE", Code: "OXALATE", Unit: "mg/L", LowRefRange: 1, HighRefRange: 5, Category: "Biochemistry", SubCategory: "Other", Description: "Oxalate levels in blood or urine."},
	{Name: "PHOSPHORUS", Code: "PHOSPHORUS", Unit: "mg/dL", LowRefRange: 2.5, HighRefRange: 4.5, Category: "Biochemistry", SubCategory: "Other", Description: "Phosphorus levels in blood."},
	{Name: "PHOSPHORUS-VERIF", Code: "PHOSPHORUS-VERIF", Unit: "mg/dL", LowRefRange: 2.5, HighRefRange: 4.5, Category: "Biochemistry", SubCategory: "Other", Description: "Phosphorus levels verification."},
	{Name: "PREALBUMIN BIR", Code: "PREALBUMIN BIR", Unit: "mg/dL", LowRefRange: 15, HighRefRange: 36, Category: "Biochemistry", SubCategory: "Other", Description: "Prealbumin levels in blood."},
	{Name: "PROTEIN TOTALBIR", Code: "PROTEIN TOTALBIR", Unit: "g/dL", LowRefRange: 6.4, HighRefRange: 8.3, Category: "Biochemistry", SubCategory: "Other", Description: "Total protein levels in blood."},
	{Name: "PROTEIN URINE", Code: "PROTEIN URINE", Unit: "mg/dL", LowRefRange: 0, HighRefRange: 20, Category: "Biochemistry", SubCategory: "Other", Description: "Protein levels in urine."},
	{Name: "RF", Code: "RF", Unit: "IU/mL", LowRefRange: 0, HighRefRange: 14, Category: "Biochemistry", SubCategory: "Other", Description: "Rheumatoid factor levels in blood."},
	{Name: "TOTAL BILE ACIDS", Code: "TOTAL BILE ACIDS", Unit: "µmol/L", LowRefRange: 0, HighRefRange: 10, Category: "Biochemistry", SubCategory: "Liver Function", Description: "Total bile acid levels in blood."},
	{Name: "TRANSFERRIN BIR", Code: "TRANSFERRIN BIR", Unit: "mg/dL", LowRefRange: 200, HighRefRange: 400, Category: "Biochemistry", SubCategory: "Metabolism", Description: "Transferrin levels in blood."},
	{Name: "TRIGLYCERIDES", Code: "TRIGLYCERIDES", Unit: "mg/dL", LowRefRange: 50, HighRefRange: 150, Category: "Biochemistry", SubCategory: "Metabolism", Description: "Blood triglyceride levels."},
	{Name: "UIBC", Code: "UIBC", Unit: "µg/dL", LowRefRange: 155, HighRefRange: 355, Category: "Biochemistry", SubCategory: "Metabolism", Description: "Unsaturated iron-binding capacity in blood."},
	{Name: "UREA-BUN-UV", Code: "UREA-BUN-UV", Unit: "mg/dL", LowRefRange: 7, HighRefRange: 20, Category: "Biochemistry", SubCategory: "Kidney Function", Description: "Urea nitrogen levels in blood using UV method."},
	{Name: "URIC ACID", Code: "URIC ACID", Unit: "mg/dL", LowRefRange: 3.5, HighRefRange: 7.2, Category: "Biochemistry", SubCategory: "Metabolism", Description: "Uric acid levels in blood."},
}

var seedDevice = []entity.Device{
	{
		ID:        1,
		Name:      "Test Device",
		IPAddress: "192.168.1.100",
		Port:      5000,
	},
}
