// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/oibacidem/lims-hl-seven/config"
	"github.com/oibacidem/lims-hl-seven/internal/delivery/rest"
	"github.com/oibacidem/lims-hl-seven/internal/delivery/tcp"
	"github.com/oibacidem/lims-hl-seven/internal/repository/sql/observation"
	"github.com/oibacidem/lims-hl-seven/internal/repository/sql/observation_request"
	"github.com/oibacidem/lims-hl-seven/internal/repository/sql/patient"
	"github.com/oibacidem/lims-hl-seven/internal/repository/sql/specimen"
	"github.com/oibacidem/lims-hl-seven/internal/repository/tcp/ba400"
	"github.com/oibacidem/lims-hl-seven/internal/usecase/analyzer"
	"github.com/oibacidem/lims-hl-seven/internal/usecase/patient"
	"github.com/oibacidem/lims-hl-seven/internal/usecase/speciment"
	"github.com/oibacidem/lims-hl-seven/internal/usecase/work_order"
	"github.com/oibacidem/lims-hl-seven/pkg/server"
)

// Injectors from wire.go:

// InitRestApp is a Wire provider function that returns a RestServer.
func InitRestApp(config2 *config.Schema) server.RestServer {
	tcp := provideTCP(config2)
	repository := ba400.NewRepository(tcp)
	db := provideDB(config2)
	specimenRepository := specimen.NewRepository(db, config2)
	observationRepository := observation.NewRepository(db, config2)
	observation_requestRepository := observation_request.NewRepository(db, config2)
	usecase := analyzer.NewUsecase(repository, specimenRepository, observationRepository, observation_requestRepository)
	hlSevenHandler := rest.NewHlSevenHandler(usecase)
	healthCheckHandler := rest.NewHealthCheckHandler(config2)
	patientRepository := patientrepo.NewPatientRepository(db, config2)
	validate := provideValidator()
	patientUseCase := patientuc.NewPatientUseCase(config2, patientRepository, validate)
	patientHandler := rest.NewPatientHandler(config2, patientUseCase)
	specimentRepository := specimentrepo.NewSpecimentRepository(db, config2)
	specimentUseCase := specimentuc.NewSpecimentUseCase(config2, specimentRepository, validate)
	specimentHandler := rest.NewSpecimentHandler(config2, specimentUseCase)
	workOrderRepository := workOrderrepo.NewWorkOrderRepository(db, config2)
	workOrderUseCase := workOrderuc.NewWorkOrderUseCase(config2, workOrderRepository, validate)
	workOrderHandler := rest.NewWorkOrderHandler(config2, workOrderUseCase)
	featureListHandler := rest.NewFeatureListHandler()
	handler := provideRestHandler(hlSevenHandler, healthCheckHandler, patientHandler, specimentHandler, workOrderHandler, featureListHandler)
	restServer := provideRestServer(config2, handler, validate)
	return restServer
}

func InitTCPApp(config2 *config.Schema) server.TCPServer {
	ba400TCP := provideTCP(config2)
	repository := ba400.NewRepository(ba400TCP)
	db := provideDB(config2)
	specimenRepository := specimen.NewRepository(db, config2)
	observationRepository := observation.NewRepository(db, config2)
	observation_requestRepository := observation_request.NewRepository(db, config2)
	usecase := analyzer.NewUsecase(repository, specimenRepository, observationRepository, observation_requestRepository)
	hlSevenHandler := tcp.NewHlSevenHandler(usecase)
	handler := provideTCPHandler(hlSevenHandler)
	tcpServer := provideTCPServer(config2, handler)
	return tcpServer
}
