// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/oibacidem/lims-hl-seven/internal/delivery/rest"
	"github.com/oibacidem/lims-hl-seven/internal/delivery/tcp"
	"github.com/oibacidem/lims-hl-seven/internal/middleware"
	"github.com/oibacidem/lims-hl-seven/internal/repository/sql/admin"
	"github.com/oibacidem/lims-hl-seven/internal/repository/sql/config"
	"github.com/oibacidem/lims-hl-seven/internal/repository/sql/daily_sequence"
	"github.com/oibacidem/lims-hl-seven/internal/repository/sql/device"
	"github.com/oibacidem/lims-hl-seven/internal/repository/sql/observation_request"
	"github.com/oibacidem/lims-hl-seven/internal/repository/sql/observation_result"
	"github.com/oibacidem/lims-hl-seven/internal/repository/sql/patient"
	"github.com/oibacidem/lims-hl-seven/internal/repository/sql/role"
	"github.com/oibacidem/lims-hl-seven/internal/repository/sql/specimen"
	"github.com/oibacidem/lims-hl-seven/internal/repository/sql/test_template"
	"github.com/oibacidem/lims-hl-seven/internal/repository/sql/test_type"
	"github.com/oibacidem/lims-hl-seven/internal/repository/sql/unit"
	"github.com/oibacidem/lims-hl-seven/internal/repository/sql/work_order"
	"github.com/oibacidem/lims-hl-seven/internal/repository/tcp/ba400"
	"github.com/oibacidem/lims-hl-seven/internal/usecase/admin"
	"github.com/oibacidem/lims-hl-seven/internal/usecase/analyzer"
	"github.com/oibacidem/lims-hl-seven/internal/usecase/auth"
	"github.com/oibacidem/lims-hl-seven/internal/usecase/barcode_generator"
	"github.com/oibacidem/lims-hl-seven/internal/usecase/config"
	"github.com/oibacidem/lims-hl-seven/internal/usecase/device"
	"github.com/oibacidem/lims-hl-seven/internal/usecase/observation_request"
	"github.com/oibacidem/lims-hl-seven/internal/usecase/patient"
	"github.com/oibacidem/lims-hl-seven/internal/usecase/result"
	"github.com/oibacidem/lims-hl-seven/internal/usecase/role"
	"github.com/oibacidem/lims-hl-seven/internal/usecase/specimen"
	"github.com/oibacidem/lims-hl-seven/internal/usecase/test_template"
	test_type2 "github.com/oibacidem/lims-hl-seven/internal/usecase/test_type"
	unit2 "github.com/oibacidem/lims-hl-seven/internal/usecase/unit"
	"github.com/oibacidem/lims-hl-seven/internal/usecase/work_order"
	"github.com/oibacidem/lims-hl-seven/pkg/server"
)

import (
	_ "github.com/golang-migrate/migrate/v4/source/file"
	_ "modernc.org/sqlite"
)

// Injectors from wire.go:

// InitRestApp is a Wire provider function that returns a RestServer.
func InitRestApp() server.RestServer {
	gormDB := provideDB()
	schema := provideConfig(gormDB)
	repository := observation_result.NewRepository(gormDB, schema)
	observation_requestRepository := observation_request.NewRepository(gormDB, schema)
	specimenRepository := specimen.NewRepository(gormDB, schema)
	cache := provideCache()
	workOrderRepository := workOrderrepo.NewWorkOrderRepository(gormDB, schema, specimenRepository, cache)
	deviceRepository := device.NewRepository(gormDB)
	ba400TCP := provideTCP(schema)
	ba400Repository := ba400.NewRepository(ba400TCP)
	usecase := analyzer.NewUsecase(repository, observation_requestRepository, specimenRepository, workOrderRepository, deviceRepository, ba400Repository)
	hlSevenHandler := rest.NewHlSevenHandler(usecase)
	healthCheckHandler := rest.NewHealthCheckHandler(schema)
	patientRepository := patientrepo.NewPatientRepository(gormDB, schema)
	validate := provideValidator()
	patientUseCase := patientuc.NewPatientUseCase(schema, patientRepository, validate)
	patientHandler := rest.NewPatientHandler(schema, patientUseCase)
	specimenUseCase := specimenuc.NewSpecimenUseCase(schema, specimenRepository, validate)
	specimenHandler := rest.NewSpecimenHandler(schema, specimenUseCase)
	daily_sequenceRepository := daily_sequence.NewRepository(gormDB)
	barcode_generatorUsecase := barcode_generator.NewUsecase(daily_sequenceRepository)
	workOrderUseCase := workOrderuc.NewWorkOrderUseCase(schema, workOrderRepository, validate, barcode_generatorUsecase)
	deviceUseCase := deviceuc.NewDeviceUseCase(deviceRepository)
	workOrderHandler := rest.NewWorkOrderHandler(schema, workOrderUseCase, gormDB, patientUseCase, deviceUseCase)
	featureListHandler := rest.NewFeatureListHandler()
	observationRequestUseCase := observation_requestuc.NewObservationRequestUseCase(schema, observation_requestRepository, validate)
	observationRequestHandler := rest.NewObservationRequestHandler(schema, observationRequestUseCase)
	test_typeRepository := test_type.NewRepository(gormDB, schema)
	test_typeUsecase := test_type2.NewUsecase(test_typeRepository)
	testTypeHandler := rest.NewTestTypeHandler(schema, test_typeUsecase)
	resultUsecase := result.NewUsecase(repository, workOrderRepository, specimenRepository, test_typeRepository)
	resultHandler := rest.NewResultHandler(schema, resultUsecase, usecase)
	configrepoRepository := configrepo.NewRepository(gormDB, schema)
	configUseCase := configuc.NewConfigUseCase(schema, configrepoRepository, validate)
	configHandler := rest.NewConfigHandler(schema, configUseCase)
	unitRepository := unit.NewRepository(gormDB, schema)
	unitUseCase := unit2.NewUnitUseCase(schema, unitRepository, validate)
	unitHandler := rest.NewUnitHandler(schema, unitUseCase)
	handler := provideRestHandler(hlSevenHandler, healthCheckHandler, patientHandler, specimenHandler, workOrderHandler, featureListHandler, observationRequestHandler, testTypeHandler, resultHandler, configHandler, unitHandler)
	deviceHandler := &rest.DeviceHandler{
		DB: gormDB,
	}
	tcpHlSevenHandler := tcp.NewHlSevenHandler(usecase)
	serverTCP := provideTCPServer(schema, tcpHlSevenHandler)
	serverControllerHandler := &rest.ServerControllerHandler{
		Cfg:       configrepoRepository,
		TCPServer: serverTCP,
	}
	test_templateRepository := test_template.NewRepository(gormDB, schema)
	test_template_ucUsecase := test_template_uc.NewUsecase(test_templateRepository)
	testTemplateHandler := rest.NewTestTemplateHandler(schema, test_template_ucUsecase)
	adminRepository := adminrepo.NewAdminRepository(gormDB, schema)
	authUseCase := auth_uc.NewAuthUseCase(adminRepository, schema)
	authHandler := rest.NewAuthHandler(authUseCase)
	roleRepository := rolerepo.NewRoleRepository(gormDB, schema)
	adminUsecase := admin_uc.NewAdminUsecase(adminRepository, roleRepository)
	adminHandler := rest.NewAdminHandler(schema, adminUsecase)
	roleUsecase := role_uc.NewRoleUsecase(roleRepository)
	roleHandler := rest.NewRoleHandler(schema, roleUsecase)
	jwtMiddleware := middleware.NewJWTMiddleware(schema)
	restServer := provideRestServer(schema, handler, validate, deviceHandler, serverControllerHandler, testTemplateHandler, authHandler, adminHandler, roleHandler, jwtMiddleware)
	return restServer
}
