// Code generated by MockGen. DO NOT EDIT.
// Source: ../usecase/analyzer.go
//
// Generated by this command:
//
//	mockgen -source=../usecase/analyzer.go -destination=./analyzer_mock.go -package=mock -typed -write_generate_directive
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/BioSystems-Indonesia/TAMALabs/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -source=../usecase/analyzer.go -destination=./analyzer_mock.go -package=mock -typed -write_generate_directive

// MockAnalyzer is a mock of Analyzer interface.
type MockAnalyzer struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyzerMockRecorder
	isgomock struct{}
}

// MockAnalyzerMockRecorder is the mock recorder for MockAnalyzer.
type MockAnalyzerMockRecorder struct {
	mock *MockAnalyzer
}

// NewMockAnalyzer creates a new mock instance.
func NewMockAnalyzer(ctrl *gomock.Controller) *MockAnalyzer {
	mock := &MockAnalyzer{ctrl: ctrl}
	mock.recorder = &MockAnalyzerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalyzer) EXPECT() *MockAnalyzerMockRecorder {
	return m.recorder
}

// ProcessORMO01 mocks base method.
func (m *MockAnalyzer) ProcessORMO01(ctx context.Context, data entity.ORM_O01) ([]entity.Specimen, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessORMO01", ctx, data)
	ret0, _ := ret[0].([]entity.Specimen)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessORMO01 indicates an expected call of ProcessORMO01.
func (mr *MockAnalyzerMockRecorder) ProcessORMO01(ctx, data any) *MockAnalyzerProcessORMO01Call {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessORMO01", reflect.TypeOf((*MockAnalyzer)(nil).ProcessORMO01), ctx, data)
	return &MockAnalyzerProcessORMO01Call{Call: call}
}

// MockAnalyzerProcessORMO01Call wrap *gomock.Call
type MockAnalyzerProcessORMO01Call struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAnalyzerProcessORMO01Call) Return(arg0 []entity.Specimen, arg1 error) *MockAnalyzerProcessORMO01Call {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAnalyzerProcessORMO01Call) Do(f func(context.Context, entity.ORM_O01) ([]entity.Specimen, error)) *MockAnalyzerProcessORMO01Call {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAnalyzerProcessORMO01Call) DoAndReturn(f func(context.Context, entity.ORM_O01) ([]entity.Specimen, error)) *MockAnalyzerProcessORMO01Call {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ProcessORUR01 mocks base method.
func (m *MockAnalyzer) ProcessORUR01(ctx context.Context, data entity.ORU_R01) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessORUR01", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessORUR01 indicates an expected call of ProcessORUR01.
func (mr *MockAnalyzerMockRecorder) ProcessORUR01(ctx, data any) *MockAnalyzerProcessORUR01Call {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessORUR01", reflect.TypeOf((*MockAnalyzer)(nil).ProcessORUR01), ctx, data)
	return &MockAnalyzerProcessORUR01Call{Call: call}
}

// MockAnalyzerProcessORUR01Call wrap *gomock.Call
type MockAnalyzerProcessORUR01Call struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAnalyzerProcessORUR01Call) Return(arg0 error) *MockAnalyzerProcessORUR01Call {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAnalyzerProcessORUR01Call) Do(f func(context.Context, entity.ORU_R01) error) *MockAnalyzerProcessORUR01Call {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAnalyzerProcessORUR01Call) DoAndReturn(f func(context.Context, entity.ORU_R01) error) *MockAnalyzerProcessORUR01Call {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ProcessOULR22 mocks base method.
func (m *MockAnalyzer) ProcessOULR22(ctx context.Context, data entity.OUL_R22) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessOULR22", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessOULR22 indicates an expected call of ProcessOULR22.
func (mr *MockAnalyzerMockRecorder) ProcessOULR22(ctx, data any) *MockAnalyzerProcessOULR22Call {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessOULR22", reflect.TypeOf((*MockAnalyzer)(nil).ProcessOULR22), ctx, data)
	return &MockAnalyzerProcessOULR22Call{Call: call}
}

// MockAnalyzerProcessOULR22Call wrap *gomock.Call
type MockAnalyzerProcessOULR22Call struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAnalyzerProcessOULR22Call) Return(arg0 error) *MockAnalyzerProcessOULR22Call {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAnalyzerProcessOULR22Call) Do(f func(context.Context, entity.OUL_R22) error) *MockAnalyzerProcessOULR22Call {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAnalyzerProcessOULR22Call) DoAndReturn(f func(context.Context, entity.OUL_R22) error) *MockAnalyzerProcessOULR22Call {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ProcessQBPQ11 mocks base method.
func (m *MockAnalyzer) ProcessQBPQ11(ctx context.Context, data entity.QBP_Q11) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessQBPQ11", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessQBPQ11 indicates an expected call of ProcessQBPQ11.
func (mr *MockAnalyzerMockRecorder) ProcessQBPQ11(ctx, data any) *MockAnalyzerProcessQBPQ11Call {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessQBPQ11", reflect.TypeOf((*MockAnalyzer)(nil).ProcessQBPQ11), ctx, data)
	return &MockAnalyzerProcessQBPQ11Call{Call: call}
}

// MockAnalyzerProcessQBPQ11Call wrap *gomock.Call
type MockAnalyzerProcessQBPQ11Call struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAnalyzerProcessQBPQ11Call) Return(arg0 error) *MockAnalyzerProcessQBPQ11Call {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAnalyzerProcessQBPQ11Call) Do(f func(context.Context, entity.QBP_Q11) error) *MockAnalyzerProcessQBPQ11Call {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAnalyzerProcessQBPQ11Call) DoAndReturn(f func(context.Context, entity.QBP_Q11) error) *MockAnalyzerProcessQBPQ11Call {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
